# Generated by Django 5.0.2 on 2024-03-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_birth_day_alter_profile_linkedin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_day',
            field=models.DateTimeField(),
        ),
    ]
