# Generated by Django 5.0.2 on 2024-03-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=2000)),
                ('last_name', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2044)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('Flowers', 'Flowers'), ('Trees', 'Trees'), ('Shrubs', 'Shrubs'), ('Vegetables', 'Vegetables')], max_length=2055)),
                ('is_edible', models.BooleanField()),
                ('craeted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
