# Generated by Django 5.0.1 on 2024-03-24 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='About',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable ', 'Vegetable'), ('Herb', 'Herb')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
            ],
        ),
    ]
