# Generated by Django 5.0.2 on 2024-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Tree', 'Tree'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Grasses', 'Grasses'), ('Shrubs', 'Shrubs'), ('Herbs', 'Herbs')], max_length=64),
        ),
    ]
