# Generated by Django 4.2.11 on 2024-03-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="category",
            field=models.CharField(
                choices=[
                    ("Fruit", "Fruit"),
                    ("Vegetable", "Vegetable"),
                    ("Flower", "Flower"),
                    ("Herb", "Herb"),
                    ("Tree", "Tree"),
                ],
                max_length=64,
            ),
        ),
    ]
