# Generated by Django 5.0.2 on 2024-03-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_addplant_plants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='image',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
