# Generated by Django 5.0.2 on 2024-03-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_craeted_at_plants_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='category',
            field=models.CharField(choices=[('Flowers', 'Flowers'), ('Trees', 'Trees'), ('Shrubs', 'Shrubs'), ('Vegetables', 'Vegetables'), ('Climbing plants', 'Climbing Plants'), ('Herbaceous plants', 'Herbaceous Plants'), ('Aquatic plants', 'Aquatic Plants')], max_length=2055),
        ),
    ]
