# Generated by Django 4.2.11 on 2024-03-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_plant_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="image",
            field=models.ImageField(
                default="images/pexels-photo-1423600.jpeg", upload_to="images/"
            ),
        ),
    ]
