# Generated by Django 5.0.2 on 2024-03-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_plants_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plants',
            old_name='category',
            new_name='categore',
        ),
    ]
