# Generated by Django 5.0.3 on 2024-03-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='plant',
        ),
    ]
