# Generated by Django 5.0.3 on 2024-03-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='context',
        ),
    ]
