# Generated by Django 5.0.2 on 2024-03-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_plants_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='category',
            field=models.CharField(choices=[('Flowers', 'Flowers'), ('Trees', 'Trees'), ('Shrubs', 'Shrubs'), ('Vegetables', 'Vegetables'), ('Climbing', 'Climbing'), ('Herbaceous', 'Herbaceous'), ('Aquatic ', 'Aquatic ')], max_length=2055),
        ),
    ]
