# Generated by Django 5.0.2 on 2024-03-23 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_category_plants_categore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plants',
            new_name='plant',
        ),
    ]
