# Generated by Django 5.0.2 on 2024-03-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_plants_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='images/plants3_D7jRXh6.png', upload_to='images/'),
        ),
    ]
