# Generated by Django 5.0.2 on 2024-03-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userinformations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='image',
            field=models.FileField(default='/images/profile-picture.png', upload_to='image/'),
        ),
    ]
