# Generated by Django 4.2.11 on 2024-03-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_comment_full_name_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="full_name",
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
