# Generated by Django 5.0.2 on 2024-03-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userinformations_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformations',
        ),
    ]
