# Generated by Django 5.0.2 on 2024-03-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_userinformations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messagee',
            new_name='message',
        ),
    ]
